FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    ansible \
    smbclient \
    openssh-server \
    sshpass \
    python3 \
    python3-pip \
    cifs-utils \
    cron \
    iputils-ping \
    sudo \
    iproute2 \
    ca-certificates \
    vim \
 && rm -rf /var/lib/apt/lists/*

EXPOSE 22
RUN wget -P /tmp/ https://products.s.kaspersky-labs.com/endpoints/keslinux10/12.3.0.1162/multilanguage-12.3.0.1162/3939393231377c44454c7c31/kesl_12.3.0-1162_amd64.deb


COPY start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

WORKDIR /workspace

CMD ["/usr/local/bin/start.sh"]
